<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SmartQuote.Shared/SmartQuote.Shared.csproj" />
    <ProjectReference Include="../SmartQuote.Modules.SupplyRequests/SmartQuote.Modules.SupplyRequests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\Persistence\EFC\Migrations\" />
  </ItemGroup>

</Project>
