// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartQuote.Modules.IdentityAccess.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartQuote.Modules.IdentityAccess.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(IdentityAccessDbContext))]
    partial class IdentityAccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartQuote.Modules.IdentityAccess.Domain.Model.Aggregates.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_normalized_email");

                    b.ToTable("user_accounts", "identity_access");
                });

            modelBuilder.Entity("SmartQuote.Modules.IdentityAccess.Domain.Model.Aggregates.UserAccount", b =>
                {
                    b.OwnsMany("SmartQuote.Modules.IdentityAccess.Domain.Model.Entities.RefreshSession", "RefreshSessions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("token_hash");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_account_id");

                            b1.HasKey("Id")
                                .HasName("pk_refresh_sessions");

                            b1.HasIndex("TokenHash")
                                .IsUnique()
                                .HasDatabaseName("ix_refresh_sessions_token_hash");

                            b1.HasIndex("user_account_id")
                                .HasDatabaseName("ix_refresh_sessions_user_account_id");

                            b1.ToTable("refresh_sessions", "identity_access");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id")
                                .HasConstraintName("fk_refresh_sessions_user_accounts_user_account_id");
                        });

                    b.OwnsMany("SmartQuote.Modules.IdentityAccess.Domain.Model.Entities.UserRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("role");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_account_id");

                            b1.HasKey("Id")
                                .HasName("pk_user_roles");

                            b1.HasIndex("user_account_id", "Role")
                                .IsUnique()
                                .HasDatabaseName("ix_user_roles_user_account_id_role");

                            b1.ToTable("user_roles", "identity_access");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id")
                                .HasConstraintName("fk_user_roles_user_accounts_user_account_id");
                        });

                    b.Navigation("RefreshSessions");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
