// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartQuote.Modules.QuotationIntake.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartQuote.Modules.QuotationIntake.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(QuotationIntakeDbContext))]
    [Migration("20260914051133_InitialQuotationIntakeModule")]
    partial class InitialQuotationIntakeModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartQuote.Modules.QuotationIntake.Domain.Model.Aggregates.PoultryQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("DeliveryLeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_lead_time_days");

                    b.Property<string>("DuplicateKey")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("character varying(110)")
                        .HasColumnName("duplicate_key");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("RequestReference")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_poultry_quotes");

                    b.HasIndex("DuplicateKey")
                        .IsUnique()
                        .HasDatabaseName("ix_poultry_quotes_duplicate_key");

                    b.ToTable("poultry_quotes", "quotation_intake");
                });

            modelBuilder.Entity("SmartQuote.Modules.QuotationIntake.Domain.Model.Aggregates.PoultryQuote", b =>
                {
                    b.OwnsOne("SmartQuote.Modules.QuotationIntake.Domain.Model.ValueObjects.SourceDocument", "SourceDocument", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("source_file_name");

                            b1.Property<string>("Sha256Hash")
                                .IsRequired()
                                .HasColumnType("char(64)")
                                .HasColumnName("source_sha256");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("source_storage_key");

                            b1.HasKey("Id")
                                .HasName("pk_poultry_quotes");

                            b1.ToTable("poultry_quotes", "quotation_intake");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_poultry_quotes_poultry_quotes_id");
                        });

                    b.OwnsOne("SmartQuote.Modules.QuotationIntake.Domain.Model.ValueObjects.SupplierReference", "Supplier", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BusinessName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("supplier_business_name");

                            b1.Property<string>("SupplierId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("supplier_reference_id");

                            b1.Property<string>("TaxIdentifier")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("supplier_tax_identifier");

                            b1.HasKey("Id")
                                .HasName("pk_poultry_quotes");

                            b1.ToTable("poultry_quotes", "quotation_intake");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_poultry_quotes_poultry_quotes_id");
                        });

                    b.OwnsMany("SmartQuote.Modules.QuotationIntake.Domain.Model.Entities.ExtractedField", "Fields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CurrentValue")
                                .HasColumnType("text")
                                .HasColumnName("current_value");

                            b1.Property<string>("FieldPath")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("field_path");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.Property<string>("OriginalValue")
                                .HasColumnType("text")
                                .HasColumnName("original_value");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("resolution_status");

                            b1.Property<Guid>("poultry_quote_id")
                                .HasColumnType("uuid")
                                .HasColumnName("poultry_quote_id");

                            b1.HasKey("Id")
                                .HasName("pk_extracted_fields");

                            b1.HasIndex("poultry_quote_id")
                                .HasDatabaseName("ix_extracted_fields_poultry_quote_id");

                            b1.ToTable("extracted_fields", "quotation_intake");

                            b1.WithOwner()
                                .HasForeignKey("poultry_quote_id")
                                .HasConstraintName("fk_extracted_fields_poultry_quotes_poultry_quote_id");

                            b1.OwnsOne("SmartQuote.Modules.QuotationIntake.Domain.Model.ValueObjects.ConfidenceScore", "Confidence", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric(5,4)")
                                        .HasColumnName("confidence");

                                    b2.HasKey("Id")
                                        .HasName("pk_extracted_fields");

                                    b2.ToTable("extracted_fields", "quotation_intake");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("fk_extracted_fields_extracted_fields_id");
                                });

                            b1.OwnsOne("SmartQuote.Modules.QuotationIntake.SourceReference", "Source", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("PageNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("source_page");

                                    b2.Property<string>("TextReference")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("source_text_reference");

                                    b2.HasKey("Id")
                                        .HasName("pk_extracted_fields");

                                    b2.ToTable("extracted_fields", "quotation_intake");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("fk_extracted_fields_extracted_fields_id");
                                });

                            b1.OwnsMany("SmartQuote.Modules.QuotationIntake.Domain.Model.Entities.FieldCorrection", "Corrections", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("CorrectedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("corrected_at");

                                    b2.Property<Guid>("CorrectedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("corrected_by");

                                    b2.Property<string>("CorrectedValue")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("corrected_value");

                                    b2.Property<string>("PreviousValue")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("previous_value");

                                    b2.Property<string>("Reason")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("reason");

                                    b2.Property<Guid>("extracted_field_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("extracted_field_id");

                                    b2.HasKey("id")
                                        .HasName("pk_field_corrections");

                                    b2.HasIndex("extracted_field_id")
                                        .HasDatabaseName("ix_field_corrections_extracted_field_id");

                                    b2.ToTable("field_corrections", "quotation_intake");

                                    b2.WithOwner()
                                        .HasForeignKey("extracted_field_id")
                                        .HasConstraintName("fk_field_corrections_extracted_fields_extracted_field_id");
                                });

                            b1.Navigation("Confidence")
                                .IsRequired();

                            b1.Navigation("Corrections");

                            b1.Navigation("Source")
                                .IsRequired();
                        });

                    b.OwnsMany("SmartQuote.Modules.QuotationIntake.Domain.Model.Entities.QuotationLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("description");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal?>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<Guid?>("RequestedItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("requested_item_id");

                            b1.Property<string>("UnitOfMeasure")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("unit_of_measure");

                            b1.Property<decimal?>("UnitPrice")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("poultry_quote_id")
                                .HasColumnType("uuid")
                                .HasColumnName("poultry_quote_id");

                            b1.HasKey("Id")
                                .HasName("pk_quotation_lines");

                            b1.HasIndex("poultry_quote_id")
                                .HasDatabaseName("ix_quotation_lines_poultry_quote_id");

                            b1.ToTable("quotation_lines", "quotation_intake");

                            b1.WithOwner()
                                .HasForeignKey("poultry_quote_id")
                                .HasConstraintName("fk_quotation_lines_poultry_quotes_poultry_quote_id");

                            b1.OwnsMany("SmartQuote.Modules.QuotationIntake.Domain.Model.ValueObjects.QuotedSpecification", "Specifications", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("name");

                                    b2.Property<string>("UnitOfMeasure")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("unit_of_measure");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("value");

                                    b2.Property<Guid>("quotation_line_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("quotation_line_id");

                                    b2.HasKey("id")
                                        .HasName("pk_quoted_specifications");

                                    b2.HasIndex("quotation_line_id")
                                        .HasDatabaseName("ix_quoted_specifications_quotation_line_id");

                                    b2.ToTable("quoted_specifications", "quotation_intake");

                                    b2.WithOwner()
                                        .HasForeignKey("quotation_line_id")
                                        .HasConstraintName("fk_quoted_specifications_quotation_lines_quotation_line_id");
                                });

                            b1.Navigation("Specifications");
                        });

                    b.Navigation("Fields");

                    b.Navigation("Lines");

                    b.Navigation("SourceDocument")
                        .IsRequired();

                    b.Navigation("Supplier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
