// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartQuote.API.PurchaseOrdering.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartQuote.Modules.PurchaseOrdering.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(PurchaseOrderingDbContext))]
    partial class PurchaseOrderingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_seq", "purchase_ordering");

            modelBuilder.Entity("SmartQuote.API.PurchaseOrdering.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_orders_order_number");

                    b.ToTable("purchase_orders", "purchase_ordering");
                });

            modelBuilder.Entity("SmartQuote.API.PurchaseOrdering.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.OwnsOne("SmartQuote.API.PurchaseOrdering.Domain.Model.ValueObjects.Approval", "Approval", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ApprovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("approved_at");

                            b1.Property<Guid>("ApprovedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("approved_by");

                            b1.Property<string>("IdempotencyKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("idempotency_key");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_orders");

                            b1.HasIndex("IdempotencyKey")
                                .IsUnique()
                                .HasDatabaseName("ix_purchase_orders_idempotency_key");

                            b1.ToTable("purchase_orders", "purchase_ordering");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_purchase_orders_purchase_orders_id");
                        });

                    b.OwnsOne("SmartQuote.API.PurchaseOrdering.Domain.Model.ValueObjects.DeliveryTerms", "DeliveryTerms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Conditions")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("delivery_conditions");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("delivery_destination");

                            b1.Property<int>("LeadTimeDays")
                                .HasColumnType("integer")
                                .HasColumnName("delivery_lead_time_days");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_orders");

                            b1.ToTable("purchase_orders", "purchase_ordering");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_purchase_orders_purchase_orders_id");
                        });

                    b.OwnsOne("SmartQuote.API.PurchaseOrdering.Domain.Model.ValueObjects.SourceSimulationReference", "SourceDecision", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("InputFingerprint")
                                .IsRequired()
                                .HasColumnType("char(64)")
                                .HasColumnName("input_fingerprint");

                            b1.Property<Guid>("PurchaseRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_purchase_request_id");

                            b1.Property<Guid>("QuotationId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_quotation_id");

                            b1.Property<Guid>("SimulationRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_simulation_run_id");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_orders");

                            b1.HasIndex("SimulationRunId")
                                .IsUnique()
                                .HasDatabaseName("ix_purchase_orders_source_simulation_run_id");

                            b1.ToTable("purchase_orders", "purchase_ordering");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_purchase_orders_purchase_orders_id");
                        });

                    b.OwnsOne("SmartQuote.API.PurchaseOrdering.Domain.Model.ValueObjects.SupplierSnapshot", "Supplier", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BusinessName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("supplier_business_name");

                            b1.Property<string>("SupplierId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("supplier_reference_id");

                            b1.Property<string>("TaxIdentifier")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("supplier_tax_identifier");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_orders");

                            b1.ToTable("purchase_orders", "purchase_ordering");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_purchase_orders_purchase_orders_id");
                        });

                    b.OwnsMany("SmartQuote.API.PurchaseOrdering.Domain.Model.Entities.PurchaseOrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("description");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<Guid?>("SourceQuotationLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_quotation_line_id");

                            b1.Property<Guid?>("SourceRequestedItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_requested_item_id");

                            b1.Property<string>("UnitOfMeasure")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("unit_of_measure");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("purchase_order_id")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_order_id");

                            b1.HasKey("Id")
                                .HasName("pk_purchase_order_lines");

                            b1.HasIndex("purchase_order_id")
                                .HasDatabaseName("ix_purchase_order_lines_purchase_order_id");

                            b1.ToTable("purchase_order_lines", "purchase_ordering");

                            b1.WithOwner()
                                .HasForeignKey("purchase_order_id")
                                .HasConstraintName("fk_purchase_order_lines_purchase_orders_purchase_order_id");
                        });

                    b.Navigation("Approval")
                        .IsRequired();

                    b.Navigation("DeliveryTerms")
                        .IsRequired();

                    b.Navigation("Lines");

                    b.Navigation("SourceDecision")
                        .IsRequired();

                    b.Navigation("Supplier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
