// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartQuote.Modules.EvaluationSimulation.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartQuote.Modules.EvaluationSimulation.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(EvaluationSimulationDbContext))]
    partial class EvaluationSimulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.EvaluationScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_scenario_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_evaluation_scenarios");

                    b.HasIndex("SupersedesScenarioId")
                        .HasDatabaseName("ix_evaluation_scenarios_supersedes_scenario_id");

                    b.HasIndex("RequestId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_evaluation_scenarios_purchase_request_id_version");

                    b.ToTable("evaluation_scenarios", "evaluation_simulation");
                });

            modelBuilder.Entity("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.SimulationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CriteriaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("criteria_version");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("input_fingerprint");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_simulation_runs");

                    b.HasIndex("ScenarioId")
                        .HasDatabaseName("ix_simulation_runs_evaluation_scenario_id");

                    b.ToTable("simulation_runs", "evaluation_simulation");
                });

            modelBuilder.Entity("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.EvaluationScenario", b =>
                {
                    b.HasOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.EvaluationScenario", null)
                        .WithMany()
                        .HasForeignKey("SupersedesScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_evaluation_scenarios_evaluation_scenarios_supersedes_scenar~");

                    b.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Entities.EvaluationCriterion", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("category");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<string>("ExpectedValue")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("expected_value");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("mode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("comparison_operator");

                            b1.Property<string>("TargetField")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("target_field");

                            b1.Property<string>("UnitOfMeasure")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("unit_of_measure");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("weight");

                            b1.Property<Guid>("evaluation_scenario_id")
                                .HasColumnType("uuid")
                                .HasColumnName("evaluation_scenario_id");

                            b1.HasKey("Id")
                                .HasName("pk_evaluation_criteria");

                            b1.HasIndex("evaluation_scenario_id")
                                .HasDatabaseName("ix_evaluation_criteria_evaluation_scenario_id");

                            b1.ToTable("evaluation_criteria", "evaluation_simulation");

                            b1.WithOwner()
                                .HasForeignKey("evaluation_scenario_id")
                                .HasConstraintName("fk_evaluation_criteria_evaluation_scenarios_evaluation_scenari~");
                        });

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.SimulationRun", b =>
                {
                    b.HasOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Aggregates.EvaluationScenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_simulation_runs_evaluation_scenarios_evaluation_scenario_id");

                    b.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.Entities.QuotationEvaluation", "Evaluations", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsEligible")
                                .HasColumnType("boolean")
                                .HasColumnName("is_eligible");

                            b1.Property<Guid>("QuotationId")
                                .HasColumnType("uuid")
                                .HasColumnName("quotation_id");

                            b1.Property<int?>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("ranking_position");

                            b1.Property<Guid>("simulation_run_id")
                                .HasColumnType("uuid")
                                .HasColumnName("simulation_run_id");

                            b1.HasKey("id")
                                .HasName("pk_quotation_evaluations");

                            b1.HasIndex("simulation_run_id")
                                .HasDatabaseName("ix_quotation_evaluations_simulation_run_id");

                            b1.ToTable("quotation_evaluations", "evaluation_simulation");

                            b1.WithOwner()
                                .HasForeignKey("simulation_run_id")
                                .HasConstraintName("fk_quotation_evaluations_simulation_runs_simulation_run_id");

                            b1.OwnsOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.Score", "TotalScore", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("total_score");

                                    b2.HasKey("id")
                                        .HasName("pk_quotation_evaluations");

                                    b2.ToTable("quotation_evaluations", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("id")
                                        .HasConstraintName("fk_quotation_evaluations_quotation_evaluations_id");
                                });

                            b1.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.CriterionResult", "CriterionResults", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<Guid>("CriterionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("evaluation_criterion_id");

                                    b2.Property<string>("Explanation")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("explanation");

                                    b2.Property<decimal>("NormalizedScore")
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("normalized_score");

                                    b2.Property<bool>("Passed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("passed");

                                    b2.Property<decimal>("WeightedContribution")
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("weighted_contribution");

                                    b2.Property<Guid>("quotation_evaluation_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("quotation_evaluation_id");

                                    b2.HasKey("id")
                                        .HasName("pk_criterion_results");

                                    b2.HasIndex("quotation_evaluation_id")
                                        .HasDatabaseName("ix_criterion_results_quotation_evaluation_id");

                                    b2.ToTable("criterion_results", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("quotation_evaluation_id")
                                        .HasConstraintName("fk_criterion_results_quotation_evaluations_quotation_evaluatio~");
                                });

                            b1.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.ExclusionReason", "ExclusionReasons", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("code");

                                    b2.Property<Guid>("CriterionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("evaluation_criterion_id");

                                    b2.Property<string>("Explanation")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("explanation");

                                    b2.Property<Guid>("quotation_evaluation_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("quotation_evaluation_id");

                                    b2.HasKey("id")
                                        .HasName("pk_exclusion_reasons");

                                    b2.HasIndex("quotation_evaluation_id")
                                        .HasDatabaseName("ix_exclusion_reasons_quotation_evaluation_id");

                                    b2.ToTable("exclusion_reasons", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("quotation_evaluation_id")
                                        .HasConstraintName("fk_exclusion_reasons_quotation_evaluations_quotation_evaluatio~");
                                });

                            b1.Navigation("CriterionResults");

                            b1.Navigation("ExclusionReasons");

                            b1.Navigation("TotalScore")
                                .IsRequired();
                        });

                    b.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.QuotationEvaluationSnapshot", "QuotationSnapshots", b1 =>
                        {
                            b1.Property<Guid>("simulation_run_id")
                                .HasColumnType("uuid")
                                .HasColumnName("simulation_run_id");

                            b1.Property<Guid>("QuotationId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_quotation_id");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("captured_at");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("currency");

                            b1.Property<int>("DeliveryLeadTimeDays")
                                .HasColumnType("integer")
                                .HasColumnName("delivery_lead_time_days");

                            b1.Property<string>("SupplierBusinessName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("supplier_business_name");

                            b1.Property<string>("SupplierId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("supplier_reference_id");

                            b1.Property<string>("SupplierTaxIdentifier")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("supplier_tax_identifier");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verified_at");

                            b1.Property<long>("Version")
                                .HasColumnType("bigint")
                                .HasColumnName("source_quotation_version");

                            b1.HasKey("simulation_run_id", "QuotationId")
                                .HasName("pk_simulation_quotation_snapshots");

                            b1.ToTable("simulation_quotation_snapshots", "evaluation_simulation");

                            b1.WithOwner()
                                .HasForeignKey("simulation_run_id")
                                .HasConstraintName("fk_simulation_quotation_snapshots_simulation_runs_simulation_r~");

                            b1.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.QuotationLineSnapshotData", "Lines", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("description");

                                    b2.Property<int>("LineNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("line_number");

                                    b2.Property<decimal>("Quantity")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("quantity");

                                    b2.Property<Guid?>("SourceQuotationLineId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("source_quotation_line_id");

                                    b2.Property<Guid?>("SourceRequestedItemId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("source_requested_item_id");

                                    b2.Property<string>("UnitOfMeasure")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("unit_of_measure");

                                    b2.Property<decimal>("UnitPrice")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("unit_price");

                                    b2.Property<Guid>("simulation_run_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("simulation_run_id");

                                    b2.Property<Guid>("source_quotation_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("source_quotation_id");

                                    b2.HasKey("id")
                                        .HasName("pk_simulation_quotation_lines");

                                    b2.HasIndex("simulation_run_id", "source_quotation_id")
                                        .HasDatabaseName("ix_simulation_quotation_lines_simulation_run_id_source_quotati~");

                                    b2.ToTable("simulation_quotation_lines", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("simulation_run_id", "source_quotation_id")
                                        .HasConstraintName("fk_simulation_quotation_lines_simulation_quotation_snapshots_s~");

                                    b2.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.QuotationSpecificationSnapshotData", "Specifications", b3 =>
                                        {
                                            b3.Property<Guid>("id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(150)
                                                .HasColumnType("character varying(150)")
                                                .HasColumnName("name");

                                            b3.Property<string>("UnitOfMeasure")
                                                .IsRequired()
                                                .HasMaxLength(30)
                                                .HasColumnType("character varying(30)")
                                                .HasColumnName("unit_of_measure");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(250)
                                                .HasColumnType("character varying(250)")
                                                .HasColumnName("value");

                                            b3.Property<Guid>("simulation_quotation_line_id")
                                                .HasColumnType("uuid")
                                                .HasColumnName("simulation_quotation_line_id");

                                            b3.HasKey("id")
                                                .HasName("pk_simulation_quotation_specifications");

                                            b3.HasIndex("simulation_quotation_line_id")
                                                .HasDatabaseName("ix_simulation_quotation_specifications_simulation_quotation_li~");

                                            b3.ToTable("simulation_quotation_specifications", "evaluation_simulation");

                                            b3.WithOwner()
                                                .HasForeignKey("simulation_quotation_line_id")
                                                .HasConstraintName("fk_simulation_quotation_specifications_simulation_quotation_li~");
                                        });

                                    b2.Navigation("Specifications");
                                });

                            b1.Navigation("Lines");
                        });

                    b.OwnsOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.Recommendation", "Recommendation", b1 =>
                        {
                            b1.Property<Guid>("simulation_run_id")
                                .HasColumnType("uuid")
                                .HasColumnName("simulation_run_id");

                            b1.Property<string>("Explanation")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("explanation");

                            b1.Property<Guid>("QuotationId")
                                .HasColumnType("uuid")
                                .HasColumnName("quotation_id");

                            b1.HasKey("simulation_run_id")
                                .HasName("pk_simulation_recommendations");

                            b1.ToTable("simulation_recommendations", "evaluation_simulation");

                            b1.WithOwner()
                                .HasForeignKey("simulation_run_id")
                                .HasConstraintName("fk_simulation_recommendations_simulation_runs_simulation_run_id");

                            b1.OwnsOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.Score", "Score", b2 =>
                                {
                                    b2.Property<Guid>("simulation_run_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("simulation_run_id");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("score");

                                    b2.HasKey("simulation_run_id")
                                        .HasName("pk_simulation_recommendations");

                                    b2.ToTable("simulation_recommendations", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("simulation_run_id")
                                        .HasConstraintName("fk_simulation_recommendations_simulation_recommendations_simul~");
                                });

                            b1.Navigation("Score")
                                .IsRequired();
                        });

                    b.OwnsOne("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.RequestEvaluationSnapshot", "RequestSnapshot", b1 =>
                        {
                            b1.Property<Guid>("simulation_run_id")
                                .HasColumnType("uuid")
                                .HasColumnName("simulation_run_id");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("captured_at");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("priority");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_request_id");

                            b1.Property<DateOnly>("RequiredDate")
                                .HasColumnType("date")
                                .HasColumnName("required_date");

                            b1.Property<long>("Version")
                                .HasColumnType("bigint")
                                .HasColumnName("source_request_version");

                            b1.HasKey("simulation_run_id")
                                .HasName("pk_simulation_request_snapshots");

                            b1.ToTable("simulation_request_snapshots", "evaluation_simulation");

                            b1.WithOwner()
                                .HasForeignKey("simulation_run_id")
                                .HasConstraintName("fk_simulation_request_snapshots_simulation_runs_simulation_run~");

                            b1.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.RequestItemSnapshotData", "Items", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("description");

                                    b2.Property<int>("LineNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("line_number");

                                    b2.Property<decimal>("Quantity")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("quantity");

                                    b2.Property<Guid>("SourceRequestedItemId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("source_requested_item_id");

                                    b2.Property<string>("UnitOfMeasure")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("unit_of_measure");

                                    b2.Property<Guid>("simulation_request_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("simulation_request_id");

                                    b2.HasKey("id")
                                        .HasName("pk_simulation_request_items");

                                    b2.HasIndex("simulation_request_id")
                                        .HasDatabaseName("ix_simulation_request_items_simulation_request_id");

                                    b2.ToTable("simulation_request_items", "evaluation_simulation");

                                    b2.WithOwner()
                                        .HasForeignKey("simulation_request_id")
                                        .HasConstraintName("fk_simulation_request_items_simulation_request_snapshots_simul~");

                                    b2.OwnsMany("SmartQuote.Modules.EvaluationSimulation.Domain.Model.ValueObjects.RequestRequirementSnapshotData", "Requirements", b3 =>
                                        {
                                            b3.Property<Guid>("id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<string>("ExpectedValue")
                                                .IsRequired()
                                                .HasMaxLength(250)
                                                .HasColumnType("character varying(250)")
                                                .HasColumnName("expected_value");

                                            b3.Property<bool>("IsMandatory")
                                                .HasColumnType("boolean")
                                                .HasColumnName("is_mandatory");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(150)
                                                .HasColumnType("character varying(150)")
                                                .HasColumnName("name");

                                            b3.Property<string>("Operator")
                                                .IsRequired()
                                                .HasMaxLength(30)
                                                .HasColumnType("character varying(30)")
                                                .HasColumnName("comparison_operator");

                                            b3.Property<Guid?>("SourceRequirementId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("source_requirement_id");

                                            b3.Property<string>("UnitOfMeasure")
                                                .IsRequired()
                                                .HasMaxLength(30)
                                                .HasColumnType("character varying(30)")
                                                .HasColumnName("unit_of_measure");

                                            b3.Property<Guid>("simulation_request_item_id")
                                                .HasColumnType("uuid")
                                                .HasColumnName("simulation_request_item_id");

                                            b3.HasKey("id")
                                                .HasName("pk_simulation_request_requirements");

                                            b3.HasIndex("simulation_request_item_id")
                                                .HasDatabaseName("ix_simulation_request_requirements_simulation_request_item_id");

                                            b3.ToTable("simulation_request_requirements", "evaluation_simulation");

                                            b3.WithOwner()
                                                .HasForeignKey("simulation_request_item_id")
                                                .HasConstraintName("fk_simulation_request_requirements_simulation_request_items_si~");
                                        });

                                    b2.Navigation("Requirements");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Evaluations");

                    b.Navigation("QuotationSnapshots");

                    b.Navigation("Recommendation");

                    b.Navigation("RequestSnapshot")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
