// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartQuote.API.SupplyRequests.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartQuote.Modules.SupplyRequests.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(SupplyRequestsDbContext))]
    [Migration("20260912000213_InitialSupplyRequestsModule")]
    partial class InitialSupplyRequestsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartQuote.API.SupplyRequests.Domain.Model.Aggregates.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<DateOnly>("RequiredDate")
                        .HasColumnType("date")
                        .HasColumnName("required_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_requests");

                    b.ToTable("purchase_requests", "supply_requests");
                });

            modelBuilder.Entity("SmartQuote.API.SupplyRequests.Infrastructure.Notifications.RequestNotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.HasKey("Id")
                        .HasName("pk_request_notifications");

                    b.HasIndex("PurchaseRequestId")
                        .HasDatabaseName("ix_request_notifications_purchase_request_id");

                    b.ToTable("request_notifications", "supply_requests");
                });

            modelBuilder.Entity("SmartQuote.API.SupplyRequests.Domain.Model.Aggregates.PurchaseRequest", b =>
                {
                    b.OwnsMany("SmartQuote.API.SupplyRequests.Domain.Model.Entities.RequestAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("storage_key");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<Guid>("UploadedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("uploaded_by");

                            b1.Property<Guid>("purchase_request_id")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_request_id");

                            b1.HasKey("Id")
                                .HasName("pk_request_attachments");

                            b1.HasIndex("purchase_request_id")
                                .HasDatabaseName("ix_request_attachments_purchase_request_id");

                            b1.ToTable("request_attachments", "supply_requests");

                            b1.WithOwner()
                                .HasForeignKey("purchase_request_id")
                                .HasConstraintName("fk_request_attachments_purchase_requests_purchase_request_id");
                        });

                    b.OwnsMany("SmartQuote.API.SupplyRequests.Domain.Model.Entities.RequestStatusEntry", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ChangedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at");

                            b1.Property<Guid>("ChangedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by");

                            b1.Property<string>("FromStatus")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("from_status");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reason");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("to_status");

                            b1.Property<Guid>("purchase_request_id")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_request_id");

                            b1.HasKey("id")
                                .HasName("pk_request_status_history");

                            b1.HasIndex("purchase_request_id")
                                .HasDatabaseName("ix_request_status_history_purchase_request_id");

                            b1.ToTable("request_status_history", "supply_requests");

                            b1.WithOwner()
                                .HasForeignKey("purchase_request_id")
                                .HasConstraintName("fk_request_status_history_purchase_requests_purchase_request_id");
                        });

                    b.OwnsMany("SmartQuote.API.SupplyRequests.Domain.Model.Entities.RequestedItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("description");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<string>("UnitOfMeasure")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("unit_of_measure");

                            b1.Property<Guid>("purchase_request_id")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_request_id");

                            b1.HasKey("Id")
                                .HasName("pk_requested_items");

                            b1.HasIndex("purchase_request_id", "LineNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_requested_items_purchase_request_id_line_number");

                            b1.ToTable("requested_items", "supply_requests");

                            b1.WithOwner()
                                .HasForeignKey("purchase_request_id")
                                .HasConstraintName("fk_requested_items_purchase_requests_purchase_request_id");

                            b1.OwnsMany("SmartQuote.API.SupplyRequests.Domain.Model.ValueObjects.TechnicalRequirement", "Requirements", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("ExpectedValue")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("expected_value");

                                    b2.Property<bool>("IsMandatory")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_mandatory");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("name");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("comparison_operator");

                                    b2.Property<string>("UnitOfMeasure")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("unit_of_measure");

                                    b2.Property<Guid>("requested_item_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("requested_item_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_technical_requirements");

                                    b2.HasIndex("requested_item_id")
                                        .HasDatabaseName("ix_technical_requirements_requested_item_id");

                                    b2.ToTable("technical_requirements", "supply_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("requested_item_id")
                                        .HasConstraintName("fk_technical_requirements_requested_items_requested_item_id");
                                });

                            b1.Navigation("Requirements");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartQuote.API.SupplyRequests.Infrastructure.Notifications.RequestNotificationRecord", b =>
                {
                    b.HasOne("SmartQuote.API.SupplyRequests.Domain.Model.Aggregates.PurchaseRequest", null)
                        .WithMany()
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_notifications_purchase_requests_purchase_request_id");
                });
#pragma warning restore 612, 618
        }
    }
}
